(* ƒvƒƒOƒ‰ƒ~ƒ“ƒO‚ÌŠî‘b: ƒƒgƒƒlƒbƒgƒ[ƒNƒf[ƒ^ (Shift_JIS ”Å) *)

let printer ppf = Format.fprintf ppf "\"%s\"";;
#install_printer printer;;

type ekimei_t = { 
  kanji   : string; (* ‰w–¼ *) 
  kana    : string; (* “Ç‚İ *) 
  romaji  : string; (* ƒ[ƒ}š *) 
  shozoku : string; (* Š‘®ü–¼ *) 
} 
 
type ekikan_t = { 
  kiten  : string; (* ‹N“_ *) 
  shuten : string; (* I“_ *) 
  keiyu  : string; (* Œo—Rü–¼ *) 
  kyori  : float;  (* ‹——£ *) 
  jikan  : int;    (* ŠÔ *) 
} 
 
let global_ekimei_list = [ 
{kanji="‘ãX–ØãŒ´"; kana="‚æ‚æ‚¬‚¤‚¦‚Í‚ç"; romaji="yoyogiuehara"; shozoku="ç‘ã“cü"}; 
{kanji="‘ãX–ØŒö‰€"; kana="‚æ‚æ‚¬‚±‚¤‚¦‚ñ"; romaji="yoyogikouen"; shozoku="ç‘ã“cü"}; 
{kanji="–¾¡_‹{‘O"; kana="‚ß‚¢‚¶‚¶‚ñ‚®‚¤‚Ü‚¦"; romaji="meijijinguumae"; shozoku="ç‘ã“cü"}; 
{kanji="•\\Q“¹"; kana="‚¨‚à‚Ä‚³‚ñ‚Ç‚¤"; romaji="omotesandou"; shozoku="ç‘ã“cü"}; 
{kanji="”T–Øâ"; kana="‚Ì‚¬‚´‚©"; romaji="nogizaka"; shozoku="ç‘ã“cü"}; 
{kanji="Ôâ"; kana="‚ ‚©‚³‚©"; romaji="akasaka"; shozoku="ç‘ã“cü"}; 
{kanji="‘‰ï‹c–“°‘O"; kana="‚±‚Á‚©‚¢‚¬‚¶‚Ç‚¤‚Ü‚¦"; romaji="kokkaigijidoumae"; shozoku="ç‘ã“cü"}; 
{kanji="‰àƒ–ŠÖ"; kana="‚©‚·‚İ‚ª‚¹‚«"; romaji="kasumigaseki"; shozoku="ç‘ã“cü"}; 
{kanji="“ú”ä’J"; kana="‚Ğ‚Ñ‚â"; romaji="hibiya"; shozoku="ç‘ã“cü"}; 
{kanji="“ñd‹´‘O"; kana="‚É‚¶‚ã‚¤‚Î‚µ‚Ü‚¦"; romaji="nijuubasimae"; shozoku="ç‘ã“cü"}; 
{kanji="‘åè’¬"; kana="‚¨‚¨‚Ä‚Ü‚¿"; romaji="otemachi"; shozoku="ç‘ã“cü"}; 
{kanji="VŒä’ƒƒm…"; kana="‚µ‚ñ‚¨‚¿‚á‚Ì‚İ‚¸"; romaji="shin-ochanomizu"; shozoku="ç‘ã“cü"}; 
{kanji="“’“‡"; kana="‚ä‚µ‚Ü"; romaji="yushima"; shozoku="ç‘ã“cü"}; 
{kanji="ª’Ã"; kana="‚Ë‚Ã"; romaji="nedu"; shozoku="ç‘ã“cü"}; 
{kanji="ç‘Ê–Ø"; kana="‚¹‚ñ‚¾‚¬"; romaji="sendagi"; shozoku="ç‘ã“cü"}; 
{kanji="¼“ú•é—¢"; kana="‚É‚µ‚É‚Á‚Û‚è"; romaji="nishinippori"; shozoku="ç‘ã“cü"}; 
{kanji="’¬‰®"; kana="‚Ü‚¿‚â"; romaji="machiya"; shozoku="ç‘ã“cü"}; 
{kanji="–kçZ"; kana="‚«‚½‚¹‚ñ‚¶‚ã"; romaji="kitasenjyu"; shozoku="ç‘ã“cü"}; 
{kanji="ˆ»£"; kana="‚ ‚â‚¹"; romaji="ayase"; shozoku="ç‘ã“cü"}; 
{kanji="–kˆ»£"; kana="‚«‚½‚ ‚â‚¹"; romaji="kitaayase"; shozoku="ç‘ã“cü"}; 
{kanji="ó‘"; kana="‚ ‚³‚­‚³"; romaji="asakusa"; shozoku="‹âÀü"}; 
{kanji="“cŒ´’¬"; kana="‚½‚í‚ç‚Ü‚¿"; romaji="tawaramachi"; shozoku="‹âÀü"}; 
{kanji="ˆî‰×’¬"; kana="‚¢‚È‚è‚¿‚å‚¤"; romaji="inaricho"; shozoku="‹âÀü"}; 
{kanji="ã–ì"; kana="‚¤‚¦‚Ì"; romaji="ueno"; shozoku="‹âÀü"}; 
{kanji="ã–ìL¬˜H"; kana="‚¤‚¦‚Ì‚Ğ‚ë‚±‚¤‚¶"; romaji="uenohirokoji"; shozoku="‹âÀü"}; 
{kanji="––L’¬"; kana="‚·‚¦‚Ğ‚ë‚¿‚å‚¤"; romaji="suehirocho"; shozoku="‹âÀü"}; 
{kanji="_“c"; kana="‚©‚ñ‚¾"; romaji="kanda"; shozoku="‹âÀü"}; 
{kanji="O‰z‘O"; kana="‚İ‚Â‚±‚µ‚Ü‚¦"; romaji="mitsukoshimae"; shozoku="‹âÀü"}; 
{kanji="“ú–{‹´"; kana="‚É‚Ù‚ñ‚Î‚µ"; romaji="nihonbashi"; shozoku="‹âÀü"}; 
{kanji="‹‹´"; kana="‚«‚å‚¤‚Î‚µ"; romaji="kyobashi"; shozoku="‹âÀü"}; 
{kanji="‹âÀ"; kana="‚¬‚ñ‚´"; romaji="ginza"; shozoku="‹âÀü"}; 
{kanji="V‹´"; kana="‚µ‚ñ‚Î‚µ"; romaji="shinbashi"; shozoku="‹âÀü"}; 
{kanji="ŒÕƒm–å"; kana="‚Æ‚ç‚Ì‚à‚ñ"; romaji="toranomon"; shozoku="‹âÀü"}; 
{kanji="—­’rR‰¤"; kana="‚½‚ß‚¢‚¯‚³‚ñ‚Ì‚¤"; romaji="tameikesannou"; shozoku="‹âÀü"}; 
{kanji="ÔâŒ©•"; kana="‚ ‚©‚³‚©‚İ‚Â‚¯"; romaji="akasakamitsuke"; shozoku="‹âÀü"}; 
{kanji="ÂRˆê’š–Ú"; kana="‚ ‚¨‚â‚Ü‚¢‚Á‚¿‚å‚¤‚ß"; romaji="aoyamaicchome"; shozoku="‹âÀü"}; 
{kanji="ŠO‰‘‘O"; kana="‚ª‚¢‚¦‚ñ‚Ü‚¦"; romaji="gaienmae"; shozoku="‹âÀü"}; 
{kanji="•\\Q“¹"; kana="‚¨‚à‚Ä‚³‚ñ‚Ç‚¤"; romaji="omotesando"; shozoku="‹âÀü"}; 
{kanji="a’J"; kana="‚µ‚Ô‚â"; romaji="shibuya"; shozoku="‹âÀü"}; 
{kanji="a’J"; kana="‚µ‚Ô‚â"; romaji="shibuya"; shozoku="”¼‘ –åü"}; 
{kanji="•\\Q“¹"; kana="‚¨‚à‚Ä‚³‚ñ‚Ç‚¤"; romaji="omotesandou"; shozoku="”¼‘ –åü"}; 
{kanji="ÂRˆê’š–Ú"; kana="‚ ‚¨‚â‚Ü‚¢‚Á‚¿‚å‚¤‚ß"; romaji="aoyama-itchome"; shozoku="”¼‘ –åü"}; 
{kanji="‰i“c’¬"; kana="‚È‚ª‚½‚¿‚å‚¤"; romaji="nagatacho"; shozoku="”¼‘ –åü"}; 
{kanji="”¼‘ –å"; kana="‚Í‚ñ‚¼‚¤‚à‚ñ"; romaji="hanzomon"; shozoku="”¼‘ –åü"}; 
{kanji="‹ã’i‰º"; kana="‚­‚¾‚ñ‚µ‚½"; romaji="kudanshita"; shozoku="”¼‘ –åü"}; 
{kanji="_•Û’¬"; kana="‚¶‚ñ‚Ú‚¤‚¿‚å‚¤"; romaji="jinbocho"; shozoku="”¼‘ –åü"}; 
{kanji="‘åè’¬"; kana="‚¨‚¨‚Ä‚Ü‚¿"; romaji="otemachi"; shozoku="”¼‘ –åü"}; 
{kanji="O‰z‘O"; kana="‚İ‚Â‚±‚µ‚Ü‚¦"; romaji="mitsukoshimae"; shozoku="”¼‘ –åü"}; 
{kanji="…“V‹{‘O"; kana="‚·‚¢‚Ä‚ñ‚®‚¤‚Ü‚¦"; romaji="suitengumae"; shozoku="”¼‘ –åü"}; 
{kanji="´Ÿ”’‰Í"; kana="‚«‚æ‚·‚İ‚µ‚ç‚©‚í"; romaji="kiyosumi-shirakawa"; shozoku="”¼‘ –åü"}; 
{kanji="Z‹g"; kana="‚·‚İ‚æ‚µ"; romaji="sumiyoshi"; shozoku="”¼‘ –åü"}; 
{kanji="‹Ñ…’¬"; kana="‚«‚ñ‚µ‚¿‚å‚¤"; romaji="kinshicho"; shozoku="”¼‘ –åü"}; 
{kanji="‰Ÿã"; kana="‚¨‚µ‚ ‚°"; romaji="oshiage"; shozoku="”¼‘ –åü"}; 
{kanji="’†–Ú•"; kana="‚È‚©‚ß‚®‚ë"; romaji="nakameguro"; shozoku="“ú”ä’Jü"}; 
{kanji="Œb”äõ"; kana="‚¦‚Ñ‚·"; romaji="ebisu"; shozoku="“ú”ä’Jü"}; 
{kanji="L”ö"; kana="‚Ğ‚ë‚¨"; romaji="hiro"; shozoku="“ú”ä’Jü"}; 
{kanji="˜Z–{–Ø"; kana="‚ë‚Á‚Û‚ñ‚¬"; romaji="roppongi"; shozoku="“ú”ä’Jü"}; 
{kanji="_’J’¬"; kana="‚©‚İ‚â‚¿‚å‚¤"; romaji="kamiyacho"; shozoku="“ú”ä’Jü"}; 
{kanji="‰àƒ–ŠÖ"; kana="‚©‚·‚İ‚ª‚¹‚«"; romaji="kasumigaseki"; shozoku="“ú”ä’Jü"}; 
{kanji="“ú”ä’J"; kana="‚Ğ‚Ñ‚â"; romaji="hibiya"; shozoku="“ú”ä’Jü"}; 
{kanji="‹âÀ"; kana="‚¬‚ñ‚´"; romaji="ginza"; shozoku="“ú”ä’Jü"}; 
{kanji="“Œ‹âÀ"; kana="‚Ğ‚ª‚µ‚¬‚ñ‚´"; romaji="higashiginza"; shozoku="“ú”ä’Jü"}; 
{kanji="’z’n"; kana="‚Â‚«‚¶"; romaji="tsukiji"; shozoku="“ú”ä’Jü"}; 
{kanji="”ª’š–x"; kana="‚Í‚Á‚¿‚å‚¤‚Ú‚è"; romaji="hacchobori"; shozoku="“ú”ä’Jü"}; 
{kanji="Šê’¬"; kana="‚©‚â‚Î‚¿‚å‚¤"; romaji="kayabacho"; shozoku="“ú”ä’Jü"}; 
{kanji="lŒ`’¬"; kana="‚É‚ñ‚¬‚å‚¤‚¿‚å‚¤"; romaji="ningyomachi"; shozoku="“ú”ä’Jü"}; 
{kanji="¬“`”n’¬"; kana="‚±‚Å‚ñ‚Ü‚¿‚å‚¤"; romaji="kodemmacho"; shozoku="“ú”ä’Jü"}; 
{kanji="H—tŒ´"; kana="‚ ‚«‚Í‚Î‚ç"; romaji="akihabara"; shozoku="“ú”ä’Jü"}; 
{kanji="’‡Œä“k’¬"; kana="‚È‚©‚¨‚©‚¿‚Ü‚¿"; romaji="nakaokachimachi"; shozoku="“ú”ä’Jü"}; 
{kanji="ã–ì"; kana="‚¤‚¦‚Ì"; romaji="ueno"; shozoku="“ú”ä’Jü"}; 
{kanji="“ü’J"; kana="‚¢‚è‚â"; romaji="iriya"; shozoku="“ú”ä’Jü"}; 
{kanji="Oƒm—Ö"; kana="‚İ‚Ì‚í"; romaji="minowa"; shozoku="“ú”ä’Jü"}; 
{kanji="“ìçZ"; kana="‚İ‚È‚İ‚¹‚ñ‚¶‚ã"; romaji="minamisenju"; shozoku="“ú”ä’Jü"}; 
{kanji="–kçZ"; kana="‚«‚½‚¹‚ñ‚¶‚ã"; romaji="kitasenju"; shozoku="“ú”ä’Jü"}; 
{kanji="’r‘Ü"; kana="‚¢‚¯‚Ô‚­‚ë"; romaji="ikebukuro"; shozoku="ŠÛƒm“àü"}; 
{kanji="V‘å’Ë"; kana="‚µ‚ñ‚¨‚¨‚Â‚©"; romaji="shinotsuka"; shozoku="ŠÛƒm“àü"}; 
{kanji="äª‰×’J"; kana="‚İ‚å‚¤‚ª‚¾‚É"; romaji="myogadani"; shozoku="ŠÛƒm“àü"}; 
{kanji="ŒãŠy‰€"; kana="‚±‚¤‚ç‚­‚¦‚ñ"; romaji="korakuen"; shozoku="ŠÛƒm“àü"}; 
{kanji="–{‹½O’š–Ú"; kana="‚Ù‚ñ‚²‚¤‚³‚ñ‚¿‚å‚¤‚ß"; romaji="hongosanchome"; shozoku="ŠÛƒm“àü"}; 
{kanji="Œä’ƒƒm…"; kana="‚¨‚¿‚á‚Ì‚İ‚¸"; romaji="ochanomizu"; shozoku="ŠÛƒm“àü"}; 
{kanji="’W˜H’¬"; kana="‚ ‚í‚¶‚¿‚å‚¤"; romaji="awajicho"; shozoku="ŠÛƒm“àü"}; 
{kanji="‘åè’¬"; kana="‚¨‚¨‚Ä‚Ü‚¿"; romaji="otemachi"; shozoku="ŠÛƒm“àü"}; 
{kanji="“Œ‹"; kana="‚Æ‚¤‚«‚å‚¤"; romaji="tokyo"; shozoku="ŠÛƒm“àü"}; 
{kanji="‹âÀ"; kana="‚¬‚ñ‚´"; romaji="ginza"; shozoku="ŠÛƒm“àü"}; 
{kanji="‰àƒ–ŠÖ"; kana="‚©‚·‚İ‚ª‚¹‚«"; romaji="kasumigaseki"; shozoku="ŠÛƒm“àü"}; 
{kanji="‘‰ï‹c–“°‘O"; kana="‚±‚Á‚©‚¢‚¬‚¶‚Ç‚¤‚Ü‚¦"; romaji="kokkaigijidomae"; shozoku="ŠÛƒm“àü"}; 
{kanji="ÔâŒ©•"; kana="‚ ‚©‚³‚©‚İ‚Â‚¯"; romaji="akasakamitsuke"; shozoku="ŠÛƒm“àü"}; 
{kanji="lƒc’J"; kana="‚æ‚Â‚â"; romaji="yotsuya"; shozoku="ŠÛƒm“àü"}; 
{kanji="l’JO’š–Ú"; kana="‚æ‚Â‚â‚³‚ñ‚¿‚å‚¤‚ß"; romaji="yotsuyasanchome"; shozoku="ŠÛƒm“àü"}; 
{kanji="VhŒä‰‘‘O"; kana="‚µ‚ñ‚¶‚ã‚­‚¬‚å‚¦‚ñ‚Ü‚¦"; romaji="shinjuku-gyoemmae"; shozoku="ŠÛƒm“àü"}; 
{kanji="VhO’š–Ú"; kana="‚µ‚ñ‚¶‚ã‚­‚³‚ñ‚¿‚å‚¤‚ß"; romaji="shinjuku-sanchome"; shozoku="ŠÛƒm“àü"}; 
{kanji="Vh"; kana="‚µ‚ñ‚¶‚ã‚­"; romaji="shinjuku"; shozoku="ŠÛƒm“àü"}; 
{kanji="¼Vh"; kana="‚É‚µ‚µ‚ñ‚¶‚ã‚­"; romaji="nishi-shinjuku"; shozoku="ŠÛƒm“àü"}; 
{kanji="’†–ìâã"; kana="‚È‚©‚Ì‚³‚©‚¤‚¦"; romaji="nakano-sakaue"; shozoku="ŠÛƒm“àü"}; 
{kanji="V’†–ì"; kana="‚µ‚ñ‚È‚©‚Ì"; romaji="shin-nakano"; shozoku="ŠÛƒm“àü"}; 
{kanji="“Œ‚‰~›"; kana="‚Ğ‚ª‚µ‚±‚¤‚¦‚ñ‚¶"; romaji="higashi-koenji"; shozoku="ŠÛƒm“àü"}; 
{kanji="V‚‰~›"; kana="‚µ‚ñ‚±‚¤‚¦‚ñ‚¶"; romaji="shin-koenji"; shozoku="ŠÛƒm“àü"}; 
{kanji="“ìˆ¢²ƒ–’J"; kana="‚İ‚È‚İ‚ ‚³‚ª‚â"; romaji="minami-asagaya"; shozoku="ŠÛƒm“àü"}; 
{kanji="‰¬ŒE"; kana="‚¨‚¬‚­‚Ú"; romaji="ogikubo"; shozoku="ŠÛƒm“àü"}; 
{kanji="’†–ìV‹´"; kana="‚È‚©‚Ì‚µ‚ñ‚Î‚µ"; romaji="nakano-shimbashi"; shozoku="ŠÛƒm“àü"}; 
{kanji="’†–ì•xmŒ©’¬"; kana="‚È‚©‚Ì‚Ó‚¶‚İ‚¿‚å‚¤"; romaji="nakano-fujimicho"; shozoku="ŠÛƒm“àü"}; 
{kanji="•û“ì’¬"; kana="‚Ù‚¤‚È‚ñ‚¿‚å‚¤"; romaji="honancho"; shozoku="ŠÛƒm“àü"}; 
{kanji="lƒc’J"; kana="‚æ‚Â‚â"; romaji="yotsuya"; shozoku="“ì–kü"}; 
{kanji="‰i“c’¬"; kana="‚È‚ª‚½‚¿‚å‚¤"; romaji="nagatacho"; shozoku="“ì–kü"}; 
{kanji="—­’rR‰¤"; kana="‚½‚ß‚¢‚¯‚³‚ñ‚Ì‚¤"; romaji="tameikesanno"; shozoku="“ì–kü"}; 
{kanji="˜Z–{–Øˆê’š–Ú"; kana="‚ë‚Á‚Û‚ñ‚¬‚¢‚Á‚¿‚å‚¤‚ß"; romaji="roppongiitchome"; shozoku="“ì–kü"}; 
{kanji="–ƒ•z\\”Ô"; kana="‚ ‚´‚Ô‚¶‚ã‚¤‚Î‚ñ"; romaji="azabujuban"; shozoku="“ì–kü"}; 
{kanji="”’‹à‚—Ö"; kana="‚µ‚ë‚©‚Ë‚½‚©‚È‚í"; romaji="shirokanetakanawa"; shozoku="“ì–kü"}; 
{kanji="”’‹à‘ä"; kana="‚µ‚ë‚©‚Ë‚¾‚¢"; romaji="shirokanedai"; shozoku="“ì–kü"}; 
{kanji="–Ú•"; kana="‚ß‚®‚ë"; romaji="meguro"; shozoku="“ì–kü"}; 
{kanji="sƒ–’J"; kana="‚¢‚¿‚ª‚â"; romaji="ichigaya"; shozoku="“ì–kü"}; 
{kanji="”Ñ“c‹´"; kana="‚¢‚¢‚¾‚Î‚µ"; romaji="idabashi"; shozoku="“ì–kü"}; 
{kanji="ŒãŠy‰€"; kana="‚±‚¤‚ç‚­‚¦‚ñ"; romaji="korakuen"; shozoku="“ì–kü"}; 
{kanji="“Œ‘å‘O"; kana="‚Æ‚¤‚¾‚¢‚Ü‚¦"; romaji="todaimae"; shozoku="“ì–kü"}; 
{kanji="–{‹î"; kana="‚Ù‚ñ‚±‚Ü‚²‚ß"; romaji="honkomagome"; shozoku="“ì–kü"}; 
{kanji="‹î"; kana="‚±‚Ü‚²‚ß"; romaji="komagome"; shozoku="“ì–kü"}; 
{kanji="¼ƒ–Œ´"; kana="‚É‚µ‚ª‚Í‚ç"; romaji="nishigahara"; shozoku="“ì–kü"}; 
{kanji="‰¤q"; kana="‚¨‚¤‚¶"; romaji="oji"; shozoku="“ì–kü"}; 
{kanji="‰¤q_’J"; kana="‚¨‚¤‚¶‚©‚İ‚â"; romaji="ojikamiya"; shozoku="“ì–kü"}; 
{kanji="u–Î"; kana="‚µ‚à"; romaji="shimo"; shozoku="“ì–kü"}; 
{kanji="Ô‰HŠâ•£"; kana="‚ ‚©‚Î‚Ë‚¢‚í‚Ô‚¿"; romaji="akabaneiwabuchi"; shozoku="“ì–kü"}; 
{kanji="¼‘D‹´"; kana="‚É‚µ‚Ó‚È‚Î‚µ"; romaji="nishi-funabashi"; shozoku="“Œ¼ü"}; 
{kanji="Œ´–Ø’†R"; kana="‚Î‚ç‚«‚È‚©‚â‚Ü"; romaji="baraki-nakayama"; shozoku="“Œ¼ü"}; 
{kanji="–­“T"; kana="‚İ‚å‚¤‚Å‚ñ"; romaji="myoden"; shozoku="“Œ¼ü"}; 
{kanji="s“¿"; kana="‚¬‚å‚¤‚Æ‚­"; romaji="gyotoku"; shozoku="“Œ¼ü"}; 
{kanji="“ìs“¿"; kana="‚İ‚È‚İ‚¬‚å‚¤‚Æ‚­"; romaji="minami-gyotoku"; shozoku="“Œ¼ü"}; 
{kanji="‰YˆÀ"; kana="‚¤‚ç‚â‚·"; romaji="urayasu"; shozoku="“Œ¼ü"}; 
{kanji="Š‹¼"; kana="‚©‚³‚¢"; romaji="kasai"; shozoku="“Œ¼ü"}; 
{kanji="¼Š‹¼"; kana="‚É‚µ‚©‚³‚¢"; romaji="nishi-kasai"; shozoku="“Œ¼ü"}; 
{kanji="“ì»’¬"; kana="‚İ‚È‚İ‚·‚È‚Ü‚¿"; romaji="minami-sunamachi"; shozoku="“Œ¼ü"}; 
{kanji="“Œ—z’¬"; kana="‚Æ‚¤‚æ‚¤‚¿‚å‚¤"; romaji="touyoucho"; shozoku="“Œ¼ü"}; 
{kanji="–Øê"; kana="‚«‚Î"; romaji="kiba"; shozoku="“Œ¼ü"}; 
{kanji="–å‘O’‡’¬"; kana="‚à‚ñ‚º‚ñ‚È‚©‚¿‚å‚¤"; romaji="monzen-nakacho"; shozoku="“Œ¼ü"}; 
{kanji="Šê’¬"; kana="‚©‚â‚Î‚¿‚å‚¤"; romaji="kayabacho"; shozoku="“Œ¼ü"}; 
{kanji="“ú–{‹´"; kana="‚É‚Ù‚ñ‚Î‚µ"; romaji="nihonbashi"; shozoku="“Œ¼ü"}; 
{kanji="‘åè’¬"; kana="‚¨‚¨‚Ä‚Ü‚¿"; romaji="otemachi"; shozoku="“Œ¼ü"}; 
{kanji="’|‹´"; kana="‚½‚¯‚Î‚µ"; romaji="takebashi"; shozoku="“Œ¼ü"}; 
{kanji="‹ã’i‰º"; kana="‚­‚¾‚ñ‚µ‚½"; romaji="kudanshita"; shozoku="“Œ¼ü"}; 
{kanji="”Ñ“c‹´"; kana="‚¢‚¢‚¾‚Î‚µ"; romaji="iidabashi"; shozoku="“Œ¼ü"}; 
{kanji="_Šyâ"; kana="‚©‚®‚ç‚´‚©"; romaji="kagurazaka"; shozoku="“Œ¼ü"}; 
{kanji="‘ˆî“c"; kana="‚í‚¹‚¾"; romaji="waseda"; shozoku="“Œ¼ü"}; 
{kanji="‚“c”nê"; kana="‚½‚©‚¾‚Ì‚Î‚Î"; romaji="takadanobaba"; shozoku="“Œ¼ü"}; 
{kanji="—‡"; kana="‚¨‚¿‚ ‚¢"; romaji="ochiai"; shozoku="“Œ¼ü"}; 
{kanji="’†–ì"; kana="‚È‚©‚Ì"; romaji="nakano"; shozoku="“Œ¼ü"}; 
{romaji="shinkiba"; kana="‚µ‚ñ‚«‚Î"; kanji="V–Øê"; shozoku="—LŠy’¬ü"}; 
{romaji="tatsumi"; kana="‚½‚Â‚İ"; kanji="’C–¤"; shozoku="—LŠy’¬ü"}; 
{romaji="toyosu"; kana="‚Æ‚æ‚·"; kanji="–LF"; shozoku="—LŠy’¬ü"}; 
{romaji="tsukishima"; kana="‚Â‚«‚µ‚Ü"; kanji="Œ“‡"; shozoku="—LŠy’¬ü"}; 
{romaji="shintomityou"; kana="‚µ‚ñ‚Æ‚İ‚¿‚å‚¤"; kanji="V•x’¬"; shozoku="—LŠy’¬ü"}; 
{romaji="ginzaittyoume"; kana="‚¬‚ñ‚´‚¢‚Á‚¿‚å‚¤‚ß"; kanji="‹âÀˆê’š–Ú"; shozoku="—LŠy’¬ü"}; 
{romaji="yuurakutyou"; kana="‚ä‚¤‚ç‚­‚¿‚å‚¤"; kanji="—LŠy’¬"; shozoku="—LŠy’¬ü"}; 
{romaji="sakuradamon"; kana="‚³‚­‚ç‚¾‚à‚ñ"; kanji="÷“c–å"; shozoku="—LŠy’¬ü"}; 
{romaji="nagatacho"; kana="‚È‚ª‚½‚¿‚å‚¤"; kanji="‰i“c’¬"; shozoku="—LŠy’¬ü"}; 
{romaji="koujimachi"; kana="‚±‚¤‚¶‚Ü‚¿"; kanji="’¬"; shozoku="—LŠy’¬ü"}; 
{romaji="ichigaya"; kana="‚¢‚¿‚ª‚â"; kanji="sƒ–’J"; shozoku="—LŠy’¬ü"}; 
{romaji="iidabashi"; kana="‚¢‚¢‚¾‚Î‚µ"; kanji="”Ñ“c‹´"; shozoku="—LŠy’¬ü"}; 
{kanji="]ŒËì‹´"; kana="‚¦‚Ç‚ª‚í‚Î‚µ"; romaji="edogawabasi"; shozoku="—LŠy’¬ü"}; 
{kanji="Œì‘›"; kana="‚²‚±‚­‚¶"; romaji="gokokuji"; shozoku="—LŠy’¬ü"}; 
{kanji="“Œ’r‘Ü"; kana="‚Ğ‚ª‚µ‚¢‚¯‚Ô‚­‚ë"; romaji="higasiikebukuro"; shozoku="—LŠy’¬ü"}; 
{kanji="’r‘Ü"; kana="‚¢‚¯‚Ô‚­‚ë"; romaji="ikebukuro"; shozoku="—LŠy’¬ü"}; 
{kanji="—v’¬"; kana="‚©‚È‚ß‚¿‚å‚¤"; romaji="kanametyou"; shozoku="—LŠy’¬ü"}; 
{kanji="çì"; kana="‚¹‚ñ‚©‚í"; romaji="senkawa"; shozoku="—LŠy’¬ü"}; 
{kanji="¬’|ŒüŒ´"; kana="‚±‚½‚¯‚Ş‚©‚¢‚Í‚ç"; romaji="kotakemukaihara"; shozoku="—LŠy’¬ü"}; 
{kanji="•Xì‘ä"; kana="‚Ğ‚©‚í‚¾‚¢"; romaji="hikawadai"; shozoku="—LŠy’¬ü"}; 
{kanji="•½˜a‘ä"; kana="‚Ö‚¢‚í‚¾‚¢"; romaji="heiwadai"; shozoku="—LŠy’¬ü"}; 
{kanji="‰c’cÔ’Ë"; kana="‚¦‚¢‚¾‚ñ‚ ‚©‚Â‚©"; romaji="eidanakakuka"; shozoku="—LŠy’¬ü"}; 
{kanji="‰c’c¬‘"; kana="‚¦‚¢‚¾‚ñ‚È‚è‚Ü‚·"; romaji="eidannarimasu"; shozoku="—LŠy’¬ü"}; 
{kanji="˜aŒõs"; kana="‚í‚±‚¤‚µ"; romaji="wakousi"; shozoku="—LŠy’¬ü"}; 
] 
let global_ekikan_list = [ 
{kiten="‘ãX–ØãŒ´"; shuten="‘ãX–ØŒö‰€"; keiyu="ç‘ã“cü"; kyori=1.0; jikan=2}; 
{kiten="‘ãX–ØŒö‰€"; shuten="–¾¡_‹{‘O"; keiyu="ç‘ã“cü"; kyori=1.2; jikan=2}; 
{kiten="–¾¡_‹{‘O"; shuten="•\\Q“¹"; keiyu="ç‘ã“cü"; kyori=0.9; jikan=2}; 
{kiten="•\\Q“¹"; shuten="”T–Øâ"; keiyu="ç‘ã“cü"; kyori=1.4; jikan=3}; 
{kiten="”T–Øâ"; shuten="Ôâ"; keiyu="ç‘ã“cü"; kyori=1.1; jikan=2}; 
{kiten="Ôâ"; shuten="‘‰ï‹c–“°‘O"; keiyu="ç‘ã“cü"; kyori=0.8; jikan=1}; 
{kiten="‘‰ï‹c–“°‘O"; shuten="‰àƒ–ŠÖ"; keiyu="ç‘ã“cü"; kyori=0.7; jikan=1}; 
{kiten="‰àƒ–ŠÖ"; shuten="“ú”ä’J"; keiyu="ç‘ã“cü"; kyori=1.2; jikan=2}; 
{kiten="“ú”ä’J"; shuten="“ñd‹´‘O"; keiyu="ç‘ã“cü"; kyori=0.7; jikan=1}; 
{kiten="“ñd‹´‘O"; shuten="‘åè’¬"; keiyu="ç‘ã“cü"; kyori=0.7; jikan=1}; 
{kiten="‘åè’¬"; shuten="VŒä’ƒƒm…"; keiyu="ç‘ã“cü"; kyori=1.3; jikan=2}; 
{kiten="VŒä’ƒƒm…"; shuten="“’“‡"; keiyu="ç‘ã“cü"; kyori=1.2; jikan=2}; 
{kiten="“’“‡"; shuten="ª’Ã"; keiyu="ç‘ã“cü"; kyori=1.2; jikan=2}; 
{kiten="ª’Ã"; shuten="ç‘Ê–Ø"; keiyu="ç‘ã“cü"; kyori=1.0; jikan=2}; 
{kiten="ç‘Ê–Ø"; shuten="¼“ú•é—¢"; keiyu="ç‘ã“cü"; kyori=0.9; jikan=1}; 
{kiten="¼“ú•é—¢"; shuten="’¬‰®"; keiyu="ç‘ã“cü"; kyori=1.7; jikan=2}; 
{kiten="’¬‰®"; shuten="–kçZ"; keiyu="ç‘ã“cü"; kyori=2.6; jikan=3}; 
{kiten="–kçZ"; shuten="ˆ»£"; keiyu="ç‘ã“cü"; kyori=2.5; jikan=3}; 
{kiten="ˆ»£"; shuten="–kˆ»£"; keiyu="ç‘ã“cü"; kyori=2.1; jikan=4}; 
{kiten="ó‘"; shuten="“cŒ´’¬"; keiyu="‹âÀü"; kyori=0.8; jikan=2}; 
{kiten="“cŒ´’¬"; shuten="ˆî‰×’¬"; keiyu="‹âÀü"; kyori=0.7; jikan=1}; 
{kiten="ˆî‰×’¬"; shuten="ã–ì"; keiyu="‹âÀü"; kyori=0.7; jikan=2}; 
{kiten="ã–ì"; shuten="ã–ìL¬˜H"; keiyu="‹âÀü"; kyori=0.5; jikan=2}; 
{kiten="ã–ìL¬˜H"; shuten="––L’¬"; keiyu="‹âÀü"; kyori=0.6; jikan=1}; 
{kiten="––L’¬"; shuten="_“c"; keiyu="‹âÀü"; kyori=1.1; jikan=2}; 
{kiten="_“c"; shuten="O‰z‘O"; keiyu="‹âÀü"; kyori=0.7; jikan=1}; 
{kiten="O‰z‘O"; shuten="“ú–{‹´"; keiyu="‹âÀü"; kyori=0.6; jikan=2}; 
{kiten="“ú–{‹´"; shuten="‹‹´"; keiyu="‹âÀü"; kyori=0.7; jikan=2}; 
{kiten="‹‹´"; shuten="‹âÀ"; keiyu="‹âÀü"; kyori=0.7; jikan=1}; 
{kiten="‹âÀ"; shuten="V‹´"; keiyu="‹âÀü"; kyori=0.9; jikan=2}; 
{kiten="V‹´"; shuten="ŒÕƒm–å"; keiyu="‹âÀü"; kyori=0.8; jikan=2}; 
{kiten="ŒÕƒm–å"; shuten="—­’rR‰¤"; keiyu="‹âÀü"; kyori=0.6; jikan=2}; 
{kiten="—­’rR‰¤"; shuten="ÔâŒ©•"; keiyu="‹âÀü"; kyori=0.9; jikan=2}; 
{kiten="ÔâŒ©•"; shuten="ÂRˆê’š–Ú"; keiyu="‹âÀü"; kyori=1.3; jikan=2}; 
{kiten="ÂRˆê’š–Ú"; shuten="ŠO‰‘‘O"; keiyu="‹âÀü"; kyori=0.7; jikan=2}; 
{kiten="ŠO‰‘‘O"; shuten="•\\Q“¹"; keiyu="‹âÀü"; kyori=0.7; jikan=1}; 
{kiten="•\\Q“¹"; shuten="a’J"; keiyu="‹âÀü"; kyori=1.3; jikan=1}; 
{kiten="a’J"; shuten="•\\Q“¹"; keiyu="”¼‘ –åü"; kyori=1.3; jikan=2}; 
{kiten="•\\Q“¹"; shuten="ÂRˆê’š–Ú"; keiyu="”¼‘ –åü"; kyori=1.4; jikan=2}; 
{kiten="ÂRˆê’š–Ú"; shuten="‰i“c’¬"; keiyu="”¼‘ –åü"; kyori=1.3; jikan=2}; 
{kiten="‰i“c’¬"; shuten="”¼‘ –å"; keiyu="”¼‘ –åü"; kyori=1.0; jikan=2}; 
{kiten="”¼‘ –å"; shuten="‹ã’i‰º"; keiyu="”¼‘ –åü"; kyori=1.6; jikan=2}; 
{kiten="‹ã’i‰º"; shuten="_•Û’¬"; keiyu="”¼‘ –åü"; kyori=0.4; jikan=1}; 
{kiten="_•Û’¬"; shuten="‘åè’¬"; keiyu="”¼‘ –åü"; kyori=1.7; jikan=3}; 
{kiten="‘åè’¬"; shuten="O‰z‘O"; keiyu="”¼‘ –åü"; kyori=0.7; jikan=1}; 
{kiten="O‰z‘O"; shuten="…“V‹{‘O"; keiyu="”¼‘ –åü"; kyori=1.3; jikan=2}; 
{kiten="…“V‹{‘O"; shuten="´Ÿ”’‰Í"; keiyu="”¼‘ –åü"; kyori=1.7; jikan=3}; 
{kiten="´Ÿ”’‰Í"; shuten="Z‹g"; keiyu="”¼‘ –åü"; kyori=1.9; jikan=3}; 
{kiten="Z‹g"; shuten="‹Ñ…’¬"; keiyu="”¼‘ –åü"; kyori=1.; jikan=2}; 
{kiten="‹Ñ…’¬"; shuten="‰Ÿã"; keiyu="”¼‘ –åü"; kyori=1.4; jikan=2}; 
{kiten="’†–Ú•"; shuten="Œb”äõ"; keiyu="“ú”ä’Jü"; kyori=1.; jikan=2}; 
{kiten="Œb”äõ"; shuten="L”ö"; keiyu="“ú”ä’Jü"; kyori=1.5; jikan=3}; 
{kiten="L”ö"; shuten="˜Z–{–Ø"; keiyu="“ú”ä’Jü"; kyori=1.7; jikan=3}; 
{kiten="˜Z–{–Ø"; shuten="_’J’¬"; keiyu="“ú”ä’Jü"; kyori=1.5; jikan=3}; 
{kiten="_’J’¬"; shuten="‰àƒ–ŠÖ"; keiyu="“ú”ä’Jü"; kyori=1.3; jikan=2}; 
{kiten="‰àƒ–ŠÖ"; shuten="“ú”ä’J"; keiyu="“ú”ä’Jü"; kyori=1.2; jikan=2}; 
{kiten="“ú”ä’J"; shuten="‹âÀ"; keiyu="“ú”ä’Jü"; kyori=0.4; jikan=1}; 
{kiten="‹âÀ"; shuten="“Œ‹âÀ"; keiyu="“ú”ä’Jü"; kyori=0.4; jikan=1}; 
{kiten="“Œ‹âÀ"; shuten="’z’n"; keiyu="“ú”ä’Jü"; kyori=0.6; jikan=2}; 
{kiten="’z’n"; shuten="”ª’š–x"; keiyu="“ú”ä’Jü"; kyori=1.; jikan=2}; 
{kiten="”ª’š–x"; shuten="Šê’¬"; keiyu="“ú”ä’Jü"; kyori=0.5; jikan=1}; 
{kiten="Šê’¬"; shuten="lŒ`’¬"; keiyu="“ú”ä’Jü"; kyori=0.9; jikan=2}; 
{kiten="lŒ`’¬"; shuten="¬“`”n’¬"; keiyu="“ú”ä’Jü"; kyori=0.6; jikan=1}; 
{kiten="¬“`”n’¬"; shuten="H—tŒ´"; keiyu="“ú”ä’Jü"; kyori=0.9; jikan=2}; 
{kiten="H—tŒ´"; shuten="’‡Œä“k’¬"; keiyu="“ú”ä’Jü"; kyori=1.; jikan=1}; 
{kiten="’‡Œä“k’¬"; shuten="ã–ì"; keiyu="“ú”ä’Jü"; kyori=0.5; jikan=1}; 
{kiten="ã–ì"; shuten="“ü’J"; keiyu="“ú”ä’Jü"; kyori=1.2; jikan=2}; 
{kiten="“ü’J"; shuten="Oƒm—Ö"; keiyu="“ú”ä’Jü"; kyori=1.2; jikan=2}; 
{kiten="Oƒm—Ö"; shuten="“ìçZ"; keiyu="“ú”ä’Jü"; kyori=0.8; jikan=2}; 
{kiten="“ìçZ"; shuten="–kçZ"; keiyu="“ú”ä’Jü"; kyori=1.8; jikan=3}; 
{kiten="’r‘Ü"; shuten="V‘å’Ë"; keiyu="ŠÛƒm“àü"; kyori=1.8; jikan=3}; 
{kiten="V‘å’Ë"; shuten="äª‰×’J"; keiyu="ŠÛƒm“àü"; kyori=1.2; jikan=2}; 
{kiten="äª‰×’J"; shuten="ŒãŠy‰€"; keiyu="ŠÛƒm“àü"; kyori=1.8; jikan=2}; 
{kiten="ŒãŠy‰€"; shuten="–{‹½O’š–Ú"; keiyu="ŠÛƒm“àü"; kyori=0.8; jikan=1}; 
{kiten="–{‹½O’š–Ú"; shuten="Œä’ƒƒm…"; keiyu="ŠÛƒm“àü"; kyori=0.8; jikan=1}; 
{kiten="Œä’ƒƒm…"; shuten="’W˜H’¬"; keiyu="ŠÛƒm“àü"; kyori=0.8; jikan=1}; 
{kiten="’W˜H’¬"; shuten="‘åè’¬"; keiyu="ŠÛƒm“àü"; kyori=0.9; jikan=2}; 
{kiten="‘åè’¬"; shuten="“Œ‹"; keiyu="ŠÛƒm“àü"; kyori=0.6; jikan=1}; 
{kiten="“Œ‹"; shuten="‹âÀ"; keiyu="ŠÛƒm“àü"; kyori=1.1; jikan=2}; 
{kiten="‹âÀ"; shuten="‰àƒ–ŠÖ"; keiyu="ŠÛƒm“àü"; kyori=1.0; jikan=2}; 
{kiten="‰àƒ–ŠÖ"; shuten="‘‰ï‹c–“°‘O"; keiyu="ŠÛƒm“àü"; kyori=0.7; jikan=1}; 
{kiten="‘‰ï‹c–“°‘O"; shuten="ÔâŒ©•"; keiyu="ŠÛƒm“àü"; kyori=0.9; jikan=2}; 
{kiten="ÔâŒ©•"; shuten="lƒc’J"; keiyu="ŠÛƒm“àü"; kyori=1.3; jikan=2}; 
{kiten="lƒc’J"; shuten="l’JO’š–Ú"; keiyu="ŠÛƒm“àü"; kyori=1.0; jikan=2}; 
{kiten="l’JO’š–Ú"; shuten="VhŒä‰‘‘O"; keiyu="ŠÛƒm“àü"; kyori=0.9; jikan=1}; 
{kiten="VhŒä‰‘‘O"; shuten="VhO’š–Ú"; keiyu="ŠÛƒm“àü"; kyori=0.7; jikan=1}; 
{kiten="VhO’š–Ú"; shuten="Vh"; keiyu="ŠÛƒm“àü"; kyori=0.3; jikan=1}; 
{kiten="Vh"; shuten="¼Vh"; keiyu="ŠÛƒm“àü"; kyori=0.8; jikan=1}; 
{kiten="¼Vh"; shuten="’†–ìâã"; keiyu="ŠÛƒm“àü"; kyori=1.1; jikan=2}; 
{kiten="’†–ìâã"; shuten="V’†–ì"; keiyu="ŠÛƒm“àü"; kyori=1.1; jikan=2}; 
{kiten="V’†–ì"; shuten="“Œ‚‰~›"; keiyu="ŠÛƒm“àü"; kyori=1.0; jikan=1}; 
{kiten="“Œ‚‰~›"; shuten="V‚‰~›"; keiyu="ŠÛƒm“àü"; kyori=0.9; jikan=1}; 
{kiten="V‚‰~›"; shuten="“ìˆ¢²ƒ–’J"; keiyu="ŠÛƒm“àü"; kyori=1.2; jikan=2}; 
{kiten="“ìˆ¢²ƒ–’J"; shuten="‰¬ŒE"; keiyu="ŠÛƒm“àü"; kyori=1.5; jikan=2}; 
{kiten="’†–ìâã"; shuten="’†–ìV‹´"; keiyu="ŠÛƒm“àü"; kyori=1.3; jikan=2}; 
{kiten="’†–ìV‹´"; shuten="’†–ì•xmŒ©’¬"; keiyu="ŠÛƒm“àü"; kyori=0.6; jikan=1}; 
{kiten="’†–ì•xmŒ©’¬"; shuten="•û“ì’¬"; keiyu="ŠÛƒm“àü"; kyori=1.3; jikan=2}; 
{kiten="sƒ–’J"; shuten="lƒc’J"; keiyu="“ì–kü"; kyori=1.0; jikan=2}; 
{kiten="lƒc’J"; shuten="‰i“c’¬"; keiyu="“ì–kü"; kyori=1.3; jikan=3}; 
{kiten="‰i“c’¬"; shuten="—­’rR‰¤"; keiyu="“ì–kü"; kyori=0.9; jikan=1}; 
{kiten="—­’rR‰¤"; shuten="˜Z–{–Øˆê’š–Ú"; keiyu="“ì–kü"; kyori=0.9; jikan=2}; 
{kiten="˜Z–{–Øˆê’š–Ú"; shuten="–ƒ•z\\”Ô"; keiyu="“ì–kü"; kyori=1.2; jikan=2}; 
{kiten="–ƒ•z\\”Ô"; shuten="”’‹à‚—Ö"; keiyu="“ì–kü"; kyori=1.3; jikan=2}; 
{kiten="”’‹à‚—Ö"; shuten="”’‹à‘ä"; keiyu="“ì–kü"; kyori=1.0; jikan=2}; 
{kiten="”’‹à‘ä"; shuten="–Ú•"; keiyu="“ì–kü"; kyori=1.3; jikan=2}; 
{kiten="sƒ–’J"; shuten="”Ñ“c‹´"; keiyu="“ì–kü"; kyori=1.1 ; jikan=2}; 
{kiten="”Ñ“c‹´"; shuten="ŒãŠy‰€"; keiyu="“ì–kü"; kyori=1.4 ; jikan=2}; 
{kiten="ŒãŠy‰€"; shuten="“Œ‘å‘O"; keiyu="“ì–kü"; kyori=1.3 ; jikan=3}; 
{kiten="“Œ‘å‘O"; shuten="–{‹î"; keiyu="“ì–kü"; kyori=0.9 ; jikan=2}; 
{kiten="–{‹î"; shuten="‹î"; keiyu="“ì–kü"; kyori=1.4; jikan=2}; 
{kiten="‹î"; shuten="¼ƒ–Œ´"; keiyu="“ì–kü"; kyori=1.4; jikan=2}; 
{kiten="¼ƒ–Œ´"; shuten="‰¤q"; keiyu="“ì–kü"; kyori=1.0; jikan=2}; 
{kiten="‰¤q"; shuten="‰¤q_’J"; keiyu="“ì–kü"; kyori=1.2; jikan=2}; 
{kiten="‰¤q_’J"; shuten="u–Î"; keiyu="“ì–kü"; kyori=1.6; jikan=3}; 
{kiten="u–Î"; shuten="Ô‰HŠâ•£"; keiyu="“ì–kü"; kyori=1.1; jikan=2}; 
{kiten="¼‘D‹´" ; shuten="Œ´–Ø’†R"; keiyu="“Œ¼ü"; kyori=1.9; jikan=3}; 
{kiten="Œ´–Ø’†R"; shuten="–­“T"; keiyu="“Œ¼ü"; kyori=2.1 ; jikan=2}; 
{kiten="–­“T"; shuten="s“¿"; keiyu="“Œ¼ü"; kyori=1.3 ; jikan=2}; 
{kiten="s“¿"; shuten="“ìs“¿"; keiyu="“Œ¼ü"; kyori=1.5 ; jikan=2}; 
{kiten="“ìs“¿"; shuten="‰YˆÀ" ; keiyu="“Œ¼ü"; kyori=1.2 ; jikan=2}; 
{kiten="‰YˆÀ" ; shuten="Š‹¼"; keiyu="“Œ¼ü"; kyori=1.9 ; jikan=2}; 
{kiten="Š‹¼"; shuten="¼Š‹¼"; keiyu="“Œ¼ü"; kyori=1.2 ; jikan=2}; 
{kiten="¼Š‹¼"; shuten="“ì»’¬"; keiyu="“Œ¼ü"; kyori=2.7 ; jikan=2}; 
{kiten="“ì»’¬"; shuten="“Œ—z’¬"; keiyu="“Œ¼ü"; kyori=1.2 ; jikan=2}; 
{kiten="“Œ—z’¬"; shuten="–Øê" ; keiyu="“Œ¼ü"; kyori=0.9 ; jikan=1}; 
{kiten="–Øê"; shuten="–å‘O’‡’¬"; keiyu="“Œ¼ü"; kyori=1.1 ; jikan=1}; 
{kiten="–å‘O’‡’¬"; shuten="Šê’¬"; keiyu="“Œ¼ü"; kyori=1.8 ; jikan=2}; 
{kiten="Šê’¬"; shuten="“ú–{‹´"; keiyu="“Œ¼ü"; kyori=0.5 ; jikan=1}; 
{kiten="“ú–{‹´"; shuten="‘åè’¬"; keiyu="“Œ¼ü"; kyori=0.8 ; jikan=1}; 
{kiten="‘åè’¬"; shuten="’|‹´"; keiyu="“Œ¼ü"; kyori=1.0; jikan=2}; 
{kiten="’|‹´"; shuten="‹ã’i‰º"; keiyu="“Œ¼ü"; kyori=1.0; jikan=1}; 
{kiten="‹ã’i‰º"; shuten="”Ñ“c‹´"; keiyu="“Œ¼ü"; kyori=0.7; jikan=1}; 
{kiten="”Ñ“c‹´"; shuten="_Šyâ"; keiyu="“Œ¼ü"; kyori=1.2; jikan=2}; 
{kiten="_Šyâ"; shuten="‘ˆî“c"; keiyu="“Œ¼ü"; kyori=1.2; jikan=2}; 
{kiten="‘ˆî“c"; shuten="‚“c”nê"; keiyu="“Œ¼ü"; kyori=1.7; jikan=3}; 
{kiten="‚“c”nê"; shuten="—‡"; keiyu="“Œ¼ü"; kyori=1.9; jikan=3}; 
{kiten="—‡"; shuten="’†–ì"; keiyu="“Œ¼ü"; kyori=2.0; jikan=3}; 
{kiten="V–Øê"; shuten="’C–¤"; keiyu="—LŠy’¬ü"; kyori=1.5; jikan=2}; 
{kiten="’C–¤"; shuten="–LF"; keiyu="—LŠy’¬ü"; kyori=1.7; jikan=2}; 
{kiten="–LF"; shuten="Œ“‡"; keiyu="—LŠy’¬ü"; kyori=1.4; jikan=2}; 
{kiten="Œ“‡"; shuten="V•x’¬"; keiyu="—LŠy’¬ü"; kyori=1.3; jikan=2}; 
{kiten="V•x’¬"; shuten="‹âÀˆê’š–Ú"; keiyu="—LŠy’¬ü"; kyori=0.7; jikan=1}; 
{kiten="‹âÀˆê’š–Ú"; shuten="—LŠy’¬"; keiyu="—LŠy’¬ü"; kyori=0.5; jikan=1}; 
{kiten="—LŠy’¬"; shuten="÷“c–å"; keiyu="—LŠy’¬ü"; kyori=1.0; jikan=1}; 
{kiten="÷“c–å"; shuten="‰i“c’¬"; keiyu="—LŠy’¬ü"; kyori=0.9; jikan=2}; 
{kiten="‰i“c’¬"; shuten="’¬"; keiyu="—LŠy’¬ü"; kyori=0.9; jikan=1}; 
{kiten="’¬"; shuten="sƒ–’J"; keiyu="—LŠy’¬ü"; kyori=0.9; jikan=1}; 
{kiten="sƒ–’J"; shuten="”Ñ“c‹´"; keiyu="—LŠy’¬ü"; kyori=1.1; jikan=2}; 
{kiten="”Ñ“c‹´"; shuten="]ŒËì‹´"; keiyu="—LŠy’¬ü"; kyori=1.6; jikan=3}; 
{kiten="]ŒËì‹´"; shuten="Œì‘›"; keiyu="—LŠy’¬ü"; kyori=1.3; jikan=2}; 
{kiten="Œì‘›"; shuten="“Œ’r‘Ü"; keiyu="—LŠy’¬ü"; kyori=1.1; jikan=2}; 
{kiten="“Œ’r‘Ü"; shuten="’r‘Ü"; keiyu="—LŠy’¬ü"; kyori=2.0; jikan=2}; 
{kiten="’r‘Ü"; shuten="—v’¬"; keiyu="—LŠy’¬ü"; kyori=1.2; jikan=2}; 
{kiten="—v’¬"; shuten="çì"; keiyu="—LŠy’¬ü"; kyori=1.0; jikan=1}; 
{kiten="çì"; shuten="¬’|ŒüŒ´"; keiyu="—LŠy’¬ü"; kyori=1.0; jikan=2}; 
{kiten="¬’|ŒüŒ´"; shuten="•Xì‘ä"; keiyu="—LŠy’¬ü"; kyori=1.5; jikan=2}; 
{kiten="•Xì‘ä"; shuten="•½˜a‘ä"; keiyu="—LŠy’¬ü"; kyori=1.4; jikan=2}; 
{kiten="•½˜a‘ä"; shuten="‰c’cÔ’Ë"; keiyu="—LŠy’¬ü"; kyori=1.8; jikan=2}; 
{kiten="‰c’cÔ’Ë"; shuten="‰c’c¬‘"; keiyu="—LŠy’¬ü"; kyori=1.5; jikan=2}; 
{kiten="‰c’c¬‘"; shuten="˜aŒõs"; keiyu="—LŠy’¬ü"; kyori=2.1; jikan=3}; 
] 
